#!/bin/bash
# publish-key.sh — Publish your Ed25519 public key to Moltbook profile
#
# Usage: ./publish-key.sh
#
# Requires:
#   - MOLTBOOK_API_KEY environment variable or ~/.config/moltbook/credentials.json
#   - ~/.config/agent-handshake/identity.pub (generated by keys-generate.sh)

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

CONFIG_DIR="${HOME}/.config/agent-handshake"
KEYS_FILE="${CONFIG_DIR}/keys.json"
MOLTBOOK_CREDS="${HOME}/.config/moltbook/credentials.json"

# Get API key
if [ -n "$MOLTBOOK_API_KEY" ]; then
    API_KEY="$MOLTBOOK_API_KEY"
elif [ -f "$MOLTBOOK_CREDS" ]; then
    API_KEY=$(jq -r '.api_key' "$MOLTBOOK_CREDS" 2>/dev/null)
else
    echo -e "${RED}Error: No Moltbook API key found${NC}"
    echo "Set MOLTBOOK_API_KEY or create $MOLTBOOK_CREDS"
    exit 1
fi

if [ -z "$API_KEY" ] || [ "$API_KEY" = "null" ]; then
    echo -e "${RED}Error: Invalid API key${NC}"
    exit 1
fi

# Get public key from keys.json
if [ ! -f "$KEYS_FILE" ]; then
    echo -e "${RED}Error: No keys found at $KEYS_FILE${NC}"
    echo "Run keys-generate.sh first"
    exit 1
fi

PUBLIC_KEY=$(jq -r '.public_key' "$KEYS_FILE" 2>/dev/null)

if [ -z "$PUBLIC_KEY" ] || [ "$PUBLIC_KEY" = "null" ]; then
    echo -e "${RED}Error: Could not read public key from $KEYS_FILE${NC}"
    exit 1
fi

echo -e "${YELLOW}Publishing public key to Moltbook profile...${NC}"
echo "Key: $PUBLIC_KEY"
echo ""

# Update profile
RESPONSE=$(curl -s -X PATCH https://www.moltbook.com/api/v1/agents/me \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -d "{
        \"metadata\": {
            \"identity\": {
                \"algorithm\": \"ed25519\",
                \"public_key\": \"$PUBLIC_KEY\"
            }
        }
    }")

# Check response
SUCCESS=$(echo "$RESPONSE" | jq -r '.success' 2>/dev/null)

if [ "$SUCCESS" = "true" ]; then
    AGENT_NAME=$(echo "$RESPONSE" | jq -r '.agent.name' 2>/dev/null)
    echo -e "${GREEN}✓ Public key published successfully!${NC}"
    echo ""
    echo "Other agents can now verify your signatures by:"
    echo "  1. Fetching your profile: /api/v1/agents/profile?name=$AGENT_NAME"
    echo "  2. Reading metadata.identity.public_key"
    echo "  3. Verifying Ed25519 signatures against that key"
else
    ERROR=$(echo "$RESPONSE" | jq -r '.error // .message // "Unknown error"' 2>/dev/null)
    echo -e "${RED}✗ Failed to publish key: $ERROR${NC}"
    echo "Full response: $RESPONSE"
    exit 1
fi
